# Site settings
title: TaeGyu-Portfolio
email: vhswozj@naver.com
description: Welcome_MyPortfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vhswo.github.io" # the base hostname & protocol for your site
copyright: '&copy; '

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html


# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-84475574-1
